# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: yuapi
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: travelmakers
# "service" is the name of this project. This will also be added to your AWS resource names.
service: hello-api

custom:
  config: ${file(../config.json)}

provider:
  name: aws
  runtime: nodejs20.x
  region: ${self:custom.config.aws.region}
  deploymentBucket:
    name: ${self:custom.config.aws.bucketName}

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: get
